version: '2'
services:
  mongo:
    image: mongo
  event-service:
    build: .
    command: java -jar /app/event-service-latest.jar
      SPRING_PROFILES_ACTIVE: docker
    port:
      - "9000:9000"
    depends_on:
      - mongo