server:
  port: 8050
  contextPath: /uaa

# actuator api access have unexpected error,you should add config:management.security.enabled=false
management:
  security:
    enabled: false

security:
  user:
    password: password
  ingored: /css/**,/js/**,/favicon.ico,/webjars/**

eureka:
  instance:
    leaserenewalintervalinseconds: 10 #服务注册检测，默认30秒，采用默认就好
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true #IP注册非HostName注册
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port} #eureka管理界面显示格式
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8010/eureka/ #,http://eureka-secondary:8011/eureka/,http://eureka-tertiary:8012/eureka/