server:
  port: ${PORT:${SERVER_PORT:8040}}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

hysrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000
---
spring:
  profiles: url
zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    path: /review-service/**
    serviceId: REVIEW # http://localhost:9010/api/review-service/reviews?eventId
  review-by-url:
    path: /review-url/**
    url: http://localhost:9010 # http://localhost:9010/api/reviews-url/review-service/eventId

---
spring:
  profiles: service

zuul:
  ingnoredServices: "*"
  prefix: /api/v1
  routes:
    event: /events/** # http:localhost:8040/api/v1/events/events
    review: /review/** #http:localhost:8040/api/v1/reviews/reviews
    event-composite: /composite/**
    recommendation: /recommendation/**

---
spring:
  profiles: docker

zuul:
  ingnoredServices: "*"
  prefix: /api/v1
  routes:
    event: /events/**
    review: /review/**
    event-composite: /composite/**
    recommendation: /recommendation/**
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8010/eureka/