version: '2' 
services:
  jenkins-slave-01: 
    container_name: jenkins-slave-01
    image: jenkins-slave-dind
    privileged: true
    environment:
      JENKINS_MASTER: 192.168.0.106:10086 
      NODE_NAME:  jenkins-slave-01 
      SECRET: 47e9eba0ab507eb78ceaa1f3845c9317a3823a6fe3a33dce7a11c06ccabf6793
    volumes:
      - /opt/jenkins_slave_home/workspace:/jenkins/workspace 
  jenkins-slave-02:
    container_name: jenkins-slave-02
    image: jenkins-slave-dind
    privileged: true
    environment:
      JENKINS_MASTER: 192.168.0.106:10086 
      NODE_NAME:  jenkins-slave-02
      SECRET: 3f79db355807fdf09c7333e9a04afa08328a0ce1ace302fa65184129b0a3d3ea
    volumes:
      - /opt/jenkins_slave_home/workspace:/jenkins/workspace   