server:
  port: 8030

eureka:
  instance:
    leaserenewalintervalinseconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

info:
  component: Turbine

turbine:
  clusterNameExpression: new String("default")
  appConfig: event-composite

---
spring:
  profiles: docker

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8010/eureka/



