server:
  port: 9050

eureka:
  instance:
    leaserenewalintervalinseconds: 10 #服务注册检测，默认30秒，采用默认就好
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

security:
  oauth2:
    resource:
      jwt:
        keyValue:
          -----BEGIN CERTIFICATE-----
          MIIDFTCCAf2gAwIBAgIEGFaptjANBgkqhkiG9w0BAQsFADA7MQswCQYDVQQGEwJE
          RTEOMAwGA1UECBMFQ2hpbmExDjAMBgNVBAcTBUNoaW5hMQwwCgYDVQQDEwNqd3Qw
          HhcNMTcwNDIzMTMxNjI2WhcNMTcwNzIyMTMxNjI2WjA7MQswCQYDVQQGEwJERTEO
          MAwGA1UECBMFQ2hpbmExDjAMBgNVBAcTBUNoaW5hMQwwCgYDVQQDEwNqd3QwggEi
          MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCcZkwcbVhDP+1r1Gdjde2VCVwe
          Kya0HHKB0WC9WFfinkhQwRQar++FM+94o1J0zGTj8dcI9IKAyzDnFaX5V0yeXvrz
          5sh0Lm2R0W9UvTHG46zJZY7BrNHzKBmZrGR4wAt43/ITIu4lP+g5v6aHjzqSsQVd
          MR4RLVPjtbzouRpWPqpOVadkpVAWBH+n0N1/VbaTVLgjuP/VxwCG9CQnTaJtZb05
          uyk7W1AcZs9io9GRNBvNrvWmEl570mYKNMODDz3b14g8PdyqJjAn3gYv+imHAHVD
          AYrcd6RCRhC0AOSOl8zOXUpHv0XP307J6H/+HPNzimhIwbTGtB+J6SMq/wl9AgMB
          AAGjITAfMB0GA1UdDgQWBBQKI+gu9EFyY7R3+sWx/DhRq08YhTANBgkqhkiG9w0B
          AQsFAAOCAQEAXb5ikn2sOoPLj1OHpcPOARabzLOgUrV54FZZLE1ZxlQGFtKbpGGq
          4CjO5q0XSYdBi/aMdv/FTl4AnGcFeRyurPYRlSsjYjwQ2KeZ0I/BKVggyd7zQ14J
          6v0GlVsehg9JdbWuJw1W3HwnXml+OECzCtUlP3foc4SqHw3EARYX1M4wjjhKq2BO
          wtyn/pfc/Iot4aqQIWNe2hln81RIqqaCV4QFthoUFqWk8B0uldukitLhfnqxm8cV
          FRrfrMcHA1xGf/nYQMP9CRSfb6WWDrCfCGv+5/kLHx5s21tZT0zyeDUlnxWIPo54
          zfUtct11T9MfGDVRVqh0vCqX5DcAnHmELQ==
          -----END CERTIFICATE-----
---
spring:
  profiles: docker

eureka:
  instance:
    preferIpAddress: true #IP注册非HostName注册
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port} #eureka管理界面显示格式
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8010/eureka/ #,http://eureka-secondary:8011/eureka/,http://eureka-tertiary:8012/eureka/

security:
  oauth2:
    resource:
      jwt:
        keyValue:
          -----BEGIN CERTIFICATE-----
          MIIDFTCCAf2gAwIBAgIEGFaptjANBgkqhkiG9w0BAQsFADA7MQswCQYDVQQGEwJE
          RTEOMAwGA1UECBMFQ2hpbmExDjAMBgNVBAcTBUNoaW5hMQwwCgYDVQQDEwNqd3Qw
          HhcNMTcwNDIzMTMxNjI2WhcNMTcwNzIyMTMxNjI2WjA7MQswCQYDVQQGEwJERTEO
          MAwGA1UECBMFQ2hpbmExDjAMBgNVBAcTBUNoaW5hMQwwCgYDVQQDEwNqd3QwggEi
          MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCcZkwcbVhDP+1r1Gdjde2VCVwe
          Kya0HHKB0WC9WFfinkhQwRQar++FM+94o1J0zGTj8dcI9IKAyzDnFaX5V0yeXvrz
          5sh0Lm2R0W9UvTHG46zJZY7BrNHzKBmZrGR4wAt43/ITIu4lP+g5v6aHjzqSsQVd
          MR4RLVPjtbzouRpWPqpOVadkpVAWBH+n0N1/VbaTVLgjuP/VxwCG9CQnTaJtZb05
          uyk7W1AcZs9io9GRNBvNrvWmEl570mYKNMODDz3b14g8PdyqJjAn3gYv+imHAHVD
          AYrcd6RCRhC0AOSOl8zOXUpHv0XP307J6H/+HPNzimhIwbTGtB+J6SMq/wl9AgMB
          AAGjITAfMB0GA1UdDgQWBBQKI+gu9EFyY7R3+sWx/DhRq08YhTANBgkqhkiG9w0B
          AQsFAAOCAQEAXb5ikn2sOoPLj1OHpcPOARabzLOgUrV54FZZLE1ZxlQGFtKbpGGq
          4CjO5q0XSYdBi/aMdv/FTl4AnGcFeRyurPYRlSsjYjwQ2KeZ0I/BKVggyd7zQ14J
          6v0GlVsehg9JdbWuJw1W3HwnXml+OECzCtUlP3foc4SqHw3EARYX1M4wjjhKq2BO
          wtyn/pfc/Iot4aqQIWNe2hln81RIqqaCV4QFthoUFqWk8B0uldukitLhfnqxm8cV
          FRrfrMcHA1xGf/nYQMP9CRSfb6WWDrCfCGv+5/kLHx5s21tZT0zyeDUlnxWIPo54
          zfUtct11T9MfGDVRVqh0vCqX5DcAnHmELQ==
          -----END CERTIFICATE-----