server:
  port: 9031

eureka:
  instance:
    leaserenewalintervalinseconds: 10
  client:
    serviceUrl:
      defaultZone: http://192.168.1.39:8010/eureka/ #,http://localhost:8011/eureka/,http://localhost:8012/eureka/

---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8010/eureka/ #,http://eureka-secondary:8011/eureka/,http://eureka-tertiary:8012/eureka/