version: '2.0'
services:
  review-service-2:
    build: .
    restart: always
    command: java -jar /app/review-service-latest.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 9011
    ports:
      - "9011:9011"