server:
  port: 9000

# actuator api access have unexpected error,you should add config:management.security.enabled=false
# "/refresh" interface also need this config 
management:
  security:
    enabled: false


eureka:
  instance:
    leaserenewalintervalinseconds: 10 #服务注册检测，默认30秒，采用默认就好
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/ #,http://localhost:8011/eureka/,http://localhost:8012/eureka/


---
spring:
  profiles: docker
  data:
    mongodb:
      host: mongo
  rabbitmq:
      host: rabbitmq  #依赖于cloud bus
eureka:
  instance:
    preferIpAddress: true #IP注册非HostName注册
    # ip-address: ${HOST} #自定义IP注册，填写docker宿主机IP便于跨机注册服务，填写方式 1：直接填写IP 2：${HOST}，并在docker-compose的environment定义HOST 3:直接在environment定义 EUREKA_INSTANCE_IP-ADDRESS: localhost
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port} #eureka管理界面显示格式
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8010/eureka/ #,http://eureka-secondary:8011/eureka/,http://eureka-tertiary:8012/eureka/