version: '2'
services:
  jenkins-master:
    image: jenkins
    container_name: jenkins-master
    ports:
      - 10086:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock